-- Create payments table for tracking layby payments
create table if not exists "public"."payments" (
    "id" bigint generated by default as identity not null,
    "deal_id" bigint not null,
    "amount" bigint not null,
    "payment_date" date not null default current_date,
    "payment_method" text not null default 'cash',
    "receipt_number" text,
    "notes" text,
    "sales_id" bigint,
    "created_at" timestamp with time zone not null default now(),
    constraint payments_pkey primary key (id),
    constraint payments_deal_id_fkey foreign key (deal_id) references deals(id) on delete cascade,
    constraint payments_sales_id_fkey foreign key (sales_id) references sales(id)
);

alter table "public"."payments" enable row level security;

-- RLS policies (same pattern as other tables - all authenticated users can CRUD)
do $$ begin
  if not exists (select 1 from pg_policies where tablename = 'payments' and policyname = 'Enable insert for authenticated users only') then
    create policy "Enable insert for authenticated users only"
    on "public"."payments" as permissive for insert to authenticated with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'payments' and policyname = 'Enable read access for authenticated users') then
    create policy "Enable read access for authenticated users"
    on "public"."payments" as permissive for select to authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'payments' and policyname = 'Enable update for authenticated users only') then
    create policy "Enable update for authenticated users only"
    on "public"."payments" as permissive for update to authenticated using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'payments' and policyname = 'Payments Delete Policy') then
    create policy "Payments Delete Policy"
    on "public"."payments" as permissive for delete to authenticated using (true);
  end if;
end $$;

-- Trigger function to auto-update deals.total_paid and stage when payments change
create or replace function update_deal_payment_totals()
returns trigger
language plpgsql
security definer
as $$
declare
  deal_total_paid bigint;
  deal_amount bigint;
  current_stage text;
begin
  select coalesce(sum(p.amount), 0) into deal_total_paid
  from payments p
  where p.deal_id = coalesce(NEW.deal_id, OLD.deal_id);

  select d.amount, d.stage into deal_amount, current_stage
  from deals d
  where d.id = coalesce(NEW.deal_id, OLD.deal_id);

  update deals
  set total_paid = deal_total_paid,
      stage = case
        when deal_total_paid >= deal_amount
          and current_stage in ('new', 'deposit-paid', 'in-progress')
          then 'paid-in-full'
        when deal_total_paid > 0
          and deal_total_paid < deal_amount
          and current_stage in ('new', 'deposit-paid')
          then 'in-progress'
        else current_stage
      end
  where id = coalesce(NEW.deal_id, OLD.deal_id);

  return coalesce(NEW, OLD);
end;
$$;

-- Triggers (drop first to be idempotent)
drop trigger if exists update_deal_totals_on_insert on payments;
create trigger update_deal_totals_on_insert
after insert on payments for each row execute function update_deal_payment_totals();

drop trigger if exists update_deal_totals_on_update on payments;
create trigger update_deal_totals_on_update
after update on payments for each row execute function update_deal_payment_totals();

drop trigger if exists update_deal_totals_on_delete on payments;
create trigger update_deal_totals_on_delete
after delete on payments for each row execute function update_deal_payment_totals();

-- Create a sequence for receipt numbers
create sequence if not exists receipt_number_seq start with 1;

-- Function to generate receipt numbers
create or replace function generate_receipt_number()
returns trigger
language plpgsql
as $$
begin
  if NEW.receipt_number is null or NEW.receipt_number = '' then
    NEW.receipt_number := 'LD-' || to_char(now(), 'YYYY') || '-' || lpad(nextval('receipt_number_seq')::text, 5, '0');
  end if;
  return NEW;
end;
$$;

drop trigger if exists set_receipt_number on payments;
create trigger set_receipt_number
before insert on payments for each row execute function generate_receipt_number();
