-- Create payment_schedule table for tracking expected installments
create table if not exists "public"."payment_schedule" (
    "id" bigint generated by default as identity not null,
    "deal_id" bigint not null,
    "installment_number" smallint not null,
    "due_date" date not null,
    "amount" bigint not null,
    "status" text not null default 'pending',
    "paid_date" date,
    "payment_id" bigint,
    constraint payment_schedule_pkey primary key (id),
    constraint payment_schedule_deal_id_fkey foreign key (deal_id) references deals(id) on delete cascade,
    constraint payment_schedule_payment_id_fkey foreign key (payment_id) references payments(id) on delete set null,
    constraint payment_schedule_status_check check (status in ('pending', 'paid', 'overdue', 'partial'))
);

alter table "public"."payment_schedule" enable row level security;

do $$ begin
  if not exists (select 1 from pg_policies where tablename = 'payment_schedule' and policyname = 'Enable insert for authenticated users only') then
    create policy "Enable insert for authenticated users only"
    on "public"."payment_schedule" as permissive for insert to authenticated with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'payment_schedule' and policyname = 'Enable read access for authenticated users') then
    create policy "Enable read access for authenticated users"
    on "public"."payment_schedule" as permissive for select to authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'payment_schedule' and policyname = 'Enable update for authenticated users only') then
    create policy "Enable update for authenticated users only"
    on "public"."payment_schedule" as permissive for update to authenticated using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'payment_schedule' and policyname = 'Payment schedule Delete Policy') then
    create policy "Payment schedule Delete Policy"
    on "public"."payment_schedule" as permissive for delete to authenticated using (true);
  end if;
end $$;

-- Function to mark overdue installments (can be called by cron or manually)
create or replace function mark_overdue_installments()
returns void
language plpgsql
security definer
as $$
begin
  update payment_schedule
  set status = 'overdue'
  where status = 'pending'
    and due_date < current_date;
end;
$$;
