-- =============================================================================
-- Migration: Adapt CRM to existing dispatch_report + payments tables
-- =============================================================================
-- On production (NZ_Archive): dispatch_report (131K rows) and payments (234K rows)
-- already exist with legacy data. Our prior migrations added broken triggers.
-- On local dev: these tables don't exist, so we create empty stubs.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1a. Drop broken triggers from existing payments table
-- ---------------------------------------------------------------------------
-- Our 20260304140000 migration added triggers referencing NEW.deal_id,
-- but on production the payments table has contract_id instead of deal_id.
DROP TRIGGER IF EXISTS update_deal_totals_on_insert ON payments;
DROP TRIGGER IF EXISTS update_deal_totals_on_update ON payments;
DROP TRIGGER IF EXISTS update_deal_totals_on_delete ON payments;
DROP TRIGGER IF EXISTS set_receipt_number ON payments;

-- ---------------------------------------------------------------------------
-- 1b. Ensure dispatch_report table exists (stub for local dev, no-op on prod)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dispatch_report (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id text,
    customer_name text,
    customer_email text,
    customer_mobile text,
    customer_phone text,
    customer_address text,
    customer_suburb text,
    customer_city text,
    customer_postcode text,
    customer_dob text,
    description text,
    make text,
    model text,
    contract_value text,
    balance text,
    installment_value text,
    term text,
    term_freq text,
    date_opened text,
    payments_received text,
    no_of_payments_due text,
    no_of_payments_cleared text,
    no_of_payments_reversed text,
    no_of_payments_missed text,
    delivery_status text,
    date_of_delivery text,
    cancelled text,
    uploaded_at timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- 1c. Create legacy_payments table/view
-- ---------------------------------------------------------------------------
-- On production, the existing "payments" table has legacy schema (dd_plan_id etc.)
-- On local dev, "payments" has CRM schema (deal_id etc.) from our prior migration.
-- We create a legacy_payments object that works in both environments.
DO $$ BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'payments' AND column_name = 'dd_plan_id'
    ) THEN
        -- Production: payments table has legacy schema, create a view over it
        EXECUTE 'CREATE OR REPLACE VIEW legacy_payments AS
            SELECT id, contract_id, dd_plan_id, payment_number,
                   scheduled_date, scheduled_amount, actual_date, actual_amount,
                   status, payment_method, dd_transaction_id, dd_status,
                   failure_reason, notes
            FROM payments';
    ELSE
        -- Local dev: create an empty table with legacy schema
        EXECUTE 'CREATE TABLE IF NOT EXISTS legacy_payments (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            contract_id text,
            dd_plan_id text,
            payment_number text,
            scheduled_date text,
            scheduled_amount text,
            actual_date text,
            actual_amount text,
            status text,
            payment_method text,
            dd_transaction_id text,
            dd_status text,
            failure_reason text,
            notes text
        )';
    END IF;
END $$;

-- ---------------------------------------------------------------------------
-- 1d. Create crm_payments table (for new CRM payment records)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS crm_payments (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    deal_id bigint NOT NULL,
    amount bigint NOT NULL,
    payment_date date NOT NULL DEFAULT current_date,
    payment_method text NOT NULL DEFAULT 'cash',
    receipt_number text,
    notes text,
    sales_id bigint,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT crm_payments_pkey PRIMARY KEY (id),
    CONSTRAINT crm_payments_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES deals(id) ON DELETE CASCADE,
    CONSTRAINT crm_payments_sales_id_fkey FOREIGN KEY (sales_id) REFERENCES sales(id)
);

ALTER TABLE crm_payments ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'crm_payments' AND policyname = 'Enable insert for authenticated users only') THEN
        CREATE POLICY "Enable insert for authenticated users only"
        ON crm_payments AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'crm_payments' AND policyname = 'Enable read access for authenticated users') THEN
        CREATE POLICY "Enable read access for authenticated users"
        ON crm_payments AS PERMISSIVE FOR SELECT TO authenticated USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'crm_payments' AND policyname = 'Enable update for authenticated users only') THEN
        CREATE POLICY "Enable update for authenticated users only"
        ON crm_payments AS PERMISSIVE FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'crm_payments' AND policyname = 'CRM Payments Delete Policy') THEN
        CREATE POLICY "CRM Payments Delete Policy"
        ON crm_payments AS PERMISSIVE FOR DELETE TO authenticated USING (true);
    END IF;
END $$;

-- Migrate any existing CRM payment data from old payments table (local dev only)
DO $$ BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'payments' AND column_name = 'deal_id'
    ) THEN
        EXECUTE 'INSERT INTO crm_payments (id, deal_id, amount, payment_date, payment_method, receipt_number, notes, sales_id, created_at)
                 SELECT id, deal_id, amount, payment_date, payment_method, receipt_number, notes, sales_id, created_at
                 FROM payments
                 ON CONFLICT (id) DO NOTHING';
        -- Update sequence to avoid id conflicts
        PERFORM setval('crm_payments_id_seq', COALESCE((SELECT MAX(id) FROM crm_payments), 0) + 1, false);
    END IF;
END $$;

-- Re-attach triggers to crm_payments
CREATE OR REPLACE FUNCTION update_deal_payment_totals()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    deal_total_paid bigint;
    deal_amount bigint;
    current_stage text;
BEGIN
    SELECT COALESCE(SUM(p.amount), 0) INTO deal_total_paid
    FROM crm_payments p
    WHERE p.deal_id = COALESCE(NEW.deal_id, OLD.deal_id);

    SELECT d.amount, d.stage INTO deal_amount, current_stage
    FROM deals d
    WHERE d.id = COALESCE(NEW.deal_id, OLD.deal_id);

    UPDATE deals
    SET total_paid = deal_total_paid,
        stage = CASE
            WHEN deal_total_paid >= deal_amount
                AND current_stage IN ('new', 'deposit-paid', 'in-progress')
                THEN 'paid-in-full'
            WHEN deal_total_paid > 0
                AND deal_total_paid < deal_amount
                AND current_stage IN ('new', 'deposit-paid')
                THEN 'in-progress'
            ELSE current_stage
        END
    WHERE id = COALESCE(NEW.deal_id, OLD.deal_id);

    RETURN COALESCE(NEW, OLD);
END;
$$;

DROP TRIGGER IF EXISTS update_deal_totals_on_insert ON crm_payments;
CREATE TRIGGER update_deal_totals_on_insert
AFTER INSERT ON crm_payments FOR EACH ROW EXECUTE FUNCTION update_deal_payment_totals();

DROP TRIGGER IF EXISTS update_deal_totals_on_update ON crm_payments;
CREATE TRIGGER update_deal_totals_on_update
AFTER UPDATE ON crm_payments FOR EACH ROW EXECUTE FUNCTION update_deal_payment_totals();

DROP TRIGGER IF EXISTS update_deal_totals_on_delete ON crm_payments;
CREATE TRIGGER update_deal_totals_on_delete
AFTER DELETE ON crm_payments FOR EACH ROW EXECUTE FUNCTION update_deal_payment_totals();

-- Receipt number trigger on crm_payments
DROP TRIGGER IF EXISTS set_receipt_number ON crm_payments;
CREATE TRIGGER set_receipt_number
BEFORE INSERT ON crm_payments FOR EACH ROW EXECUTE FUNCTION generate_receipt_number();

-- Fix payment_schedule FK to point to crm_payments instead of payments
DO $$ BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'payment_schedule_payment_id_fkey'
        AND table_name = 'payment_schedule'
    ) THEN
        ALTER TABLE payment_schedule DROP CONSTRAINT payment_schedule_payment_id_fkey;
    END IF;
END $$;

ALTER TABLE payment_schedule
    ADD CONSTRAINT payment_schedule_payment_id_fkey
    FOREIGN KEY (payment_id) REFERENCES crm_payments(id) ON DELETE SET NULL;

-- ---------------------------------------------------------------------------
-- 1e. Add source/legacy_id columns to deals table
-- ---------------------------------------------------------------------------
ALTER TABLE deals ADD COLUMN IF NOT EXISTS source text DEFAULT 'new';
ALTER TABLE deals ADD COLUMN IF NOT EXISTS legacy_id text;

-- ---------------------------------------------------------------------------
-- 2. Create deals_unified view
-- ---------------------------------------------------------------------------
-- Helper function to safely cast text to numeric (handles empty strings, non-numeric values)
CREATE OR REPLACE FUNCTION safe_numeric(txt text)
RETURNS numeric
LANGUAGE plpgsql IMMUTABLE
AS $$
BEGIN
    IF txt IS NULL OR TRIM(txt) = '' THEN RETURN NULL; END IF;
    RETURN TRIM(txt)::numeric;
EXCEPTION WHEN OTHERS THEN
    RETURN NULL;
END;
$$;

-- Helper function to parse DD/MM/YYYY dates from dispatch_report
CREATE OR REPLACE FUNCTION parse_ddmmyyyy(txt text)
RETURNS date
LANGUAGE plpgsql IMMUTABLE
AS $$
BEGIN
    IF txt IS NULL OR TRIM(txt) = '' THEN RETURN NULL; END IF;
    -- Try DD/MM/YYYY format
    BEGIN
        RETURN to_date(TRIM(txt), 'DD/MM/YYYY');
    EXCEPTION WHEN OTHERS THEN
        -- Try ISO format as fallback
        BEGIN
            RETURN TRIM(txt)::date;
        EXCEPTION WHEN OTHERS THEN
            RETURN NULL;
        END;
    END;
END;
$$;

CREATE OR REPLACE VIEW deals_unified AS
-- CRM deals (new records)
SELECT
    d.id,
    d.name,
    d.company_id,
    d.contact_ids,
    d.category,
    d.stage,
    d.description,
    d.amount,
    d.created_at,
    d.updated_at,
    d.archived_at,
    d.expected_closing_date,
    d.sales_id,
    d.index,
    d.item_description,
    d.deposit_amount,
    d.payment_frequency,
    d.next_payment_date,
    d.total_paid,
    d.contract_end_date,
    d.item_held_location,
    COALESCE(d.source, 'new') AS source,
    d.legacy_id
FROM deals d

UNION ALL

-- Legacy dispatch_report records
SELECT
    (1000000 + dr.id)::bigint AS id,
    dr.customer_name AS name,
    NULL::bigint AS company_id,
    ARRAY[]::bigint[] AS contact_ids,
    NULL::text AS category,
    CASE
        WHEN dr.cancelled = 'Closed' THEN 'collected'
        WHEN COALESCE(safe_numeric(dr.balance::text), 0) = 0 THEN 'paid-in-full'
        WHEN COALESCE(NULLIF(dr.payments_received, ''), '0') != '0' THEN 'in-progress'
        ELSE 'new'
    END AS stage,
    NULLIF(CONCAT_WS(' - ', NULLIF(dr.description, ''), NULLIF(CONCAT_WS(' ', NULLIF(dr.make, ''), NULLIF(dr.model, '')), '')), '') AS description,
    COALESCE(safe_numeric(dr.contract_value::text), 0)::bigint AS amount,
    COALESCE(parse_ddmmyyyy(dr.date_opened::text), dr.uploaded_at)::timestamptz AS created_at,
    COALESCE(parse_ddmmyyyy(dr.date_opened::text), dr.uploaded_at)::timestamptz AS updated_at,
    CASE
        WHEN dr.cancelled = 'Closed' THEN dr.uploaded_at
        ELSE NULL::timestamptz
    END AS archived_at,
    parse_ddmmyyyy(dr.date_opened::text)::date AS expected_closing_date,
    NULL::bigint AS sales_id,
    0::smallint AS index,
    NULLIF(CONCAT_WS(' ', NULLIF(dr.description, ''), NULLIF(dr.make, ''), NULLIF(dr.model, '')), '') AS item_description,
    COALESCE(safe_numeric(dr.installment_value::text), 0)::bigint AS deposit_amount,
    CASE
        WHEN dr.term_freq = 'w' THEN 'weekly'
        WHEN dr.term_freq = 'f' THEN 'fortnightly'
        ELSE 'weekly'
    END AS payment_frequency,
    NULL::date AS next_payment_date,
    (COALESCE(safe_numeric(dr.contract_value::text), 0) - COALESCE(safe_numeric(dr.balance::text), 0))::bigint AS total_paid,
    NULL::date AS contract_end_date,
    NULL::text AS item_held_location,
    'legacy'::text AS source,
    dr.plan_id AS legacy_id
FROM dispatch_report dr;

-- ---------------------------------------------------------------------------
-- 3. Create payments_crm view
-- ---------------------------------------------------------------------------
CREATE OR REPLACE VIEW payments_crm AS
-- CRM payments (new records)
SELECT
    cp.id,
    cp.deal_id,
    cp.amount,
    cp.payment_date,
    cp.payment_method,
    cp.receipt_number,
    cp.notes,
    cp.sales_id,
    cp.created_at,
    'new'::text AS source
FROM crm_payments cp

UNION ALL

-- Legacy payments (completed only, shown as payment history)
SELECT
    (10000000 + lp.id)::bigint AS id,
    (1000000 + dr.id)::bigint AS deal_id,
    COALESCE(safe_numeric(lp.actual_amount::text), safe_numeric(lp.scheduled_amount::text), 0)::bigint AS amount,
    COALESCE(parse_ddmmyyyy(lp.actual_date::text), parse_ddmmyyyy(lp.scheduled_date::text), now()::date) AS payment_date,
    COALESCE(lp.payment_method, 'Direct Debit') AS payment_method,
    lp.dd_transaction_id AS receipt_number,
    lp.notes,
    NULL::bigint AS sales_id,
    COALESCE(parse_ddmmyyyy(lp.actual_date::text), now())::timestamptz AS created_at,
    'legacy'::text AS source
FROM legacy_payments lp
JOIN dispatch_report dr ON lp.dd_plan_id = dr.plan_id
WHERE lp.status = 'completed';

-- ---------------------------------------------------------------------------
-- 4. Create payment_schedule_crm view
-- ---------------------------------------------------------------------------
CREATE OR REPLACE VIEW payment_schedule_crm AS
-- CRM payment schedule (new records)
SELECT
    ps.id,
    ps.deal_id,
    ps.installment_number,
    ps.due_date,
    ps.amount,
    ps.status,
    ps.paid_date,
    ps.payment_id,
    'new'::text AS source
FROM payment_schedule ps

UNION ALL

-- Legacy payments as schedule items
SELECT
    (10000000 + lp.id)::bigint AS id,
    (1000000 + dr.id)::bigint AS deal_id,
    COALESCE(safe_numeric(lp.payment_number::text), 0)::smallint AS installment_number,
    COALESCE(parse_ddmmyyyy(lp.scheduled_date::text), now()::date) AS due_date,
    COALESCE(safe_numeric(lp.scheduled_amount::text), 0)::bigint AS amount,
    CASE
        WHEN lp.status = 'completed' THEN 'paid'
        WHEN lp.status = 'failed' THEN 'overdue'
        ELSE 'pending'
    END::text AS status,
    CASE
        WHEN lp.status = 'completed' THEN parse_ddmmyyyy(lp.actual_date::text)
        ELSE NULL::date
    END AS paid_date,
    NULL::bigint AS payment_id,
    'legacy'::text AS source
FROM legacy_payments lp
JOIN dispatch_report dr ON lp.dd_plan_id = dr.plan_id;

-- ---------------------------------------------------------------------------
-- 5. Update contacts_summary to include legacy customers
-- ---------------------------------------------------------------------------
DROP VIEW IF EXISTS contacts_summary;

CREATE VIEW contacts_summary AS
-- Existing CRM contacts
SELECT
    co.id,
    co.first_name,
    co.last_name,
    co.gender,
    co.title,
    co.email_jsonb,
    jsonb_path_query_array(co.email_jsonb, '$[*].email')::text AS email_fts,
    co.phone_jsonb,
    jsonb_path_query_array(co.phone_jsonb, '$[*].number')::text AS phone_fts,
    co.background,
    co.avatar,
    co.first_seen,
    co.last_seen,
    co.has_newsletter,
    co.status,
    co.tags,
    co.company_id,
    co.sales_id,
    co.linkedin_url,
    co.preferred_contact_method,
    co.date_of_birth,
    c.name AS company_name,
    COUNT(DISTINCT t.id) AS nb_tasks,
    'new'::text AS source
FROM contacts co
LEFT JOIN tasks t ON co.id = t.contact_id AND t.done_date IS NULL
LEFT JOIN companies c ON co.company_id = c.id
GROUP BY co.id, c.name

UNION ALL

-- Legacy customers extracted from dispatch_report
SELECT
    lc.id,
    lc.first_name,
    lc.last_name,
    NULL::text AS gender,
    NULL::text AS title,
    lc.email_jsonb,
    lc.email_fts,
    lc.phone_jsonb,
    lc.phone_fts,
    lc.background,
    NULL::jsonb AS avatar,
    lc.first_seen,
    lc.first_seen AS last_seen,
    false AS has_newsletter,
    'active'::text AS status,
    ARRAY[]::bigint[] AS tags,
    NULL::bigint AS company_id,
    NULL::bigint AS sales_id,
    NULL::text AS linkedin_url,
    'phone'::text AS preferred_contact_method,
    lc.date_of_birth,
    NULL::text AS company_name,
    0::bigint AS nb_tasks,
    'legacy'::text AS source
FROM (
    SELECT DISTINCT ON (dedup_key)
        (2000000 + ROW_NUMBER() OVER (ORDER BY MIN(dr.id)))::bigint AS id,
        -- Parse "Last, First" into first_name / last_name
        CASE
            WHEN POSITION(',' IN dr.customer_name) > 0
            THEN TRIM(SUBSTRING(dr.customer_name FROM POSITION(',' IN dr.customer_name) + 1))
            ELSE dr.customer_name
        END AS first_name,
        CASE
            WHEN POSITION(',' IN dr.customer_name) > 0
            THEN TRIM(SUBSTRING(dr.customer_name FOR POSITION(',' IN dr.customer_name) - 1))
            ELSE ''
        END AS last_name,
        -- Email as JSONB array
        CASE
            WHEN dr.customer_email IS NOT NULL AND dr.customer_email != ''
            THEN jsonb_build_array(jsonb_build_object('email', dr.customer_email, 'type', 'Home'))
            ELSE '[]'::jsonb
        END AS email_jsonb,
        COALESCE(dr.customer_email, '') AS email_fts,
        -- Phone numbers as JSONB array
        (
            SELECT COALESCE(jsonb_agg(phone_entry), '[]'::jsonb)
            FROM (
                SELECT jsonb_build_object('number', dr.customer_phone, 'type', 'Home') AS phone_entry
                WHERE dr.customer_phone IS NOT NULL AND dr.customer_phone != ''
                UNION ALL
                SELECT jsonb_build_object('number', dr.customer_mobile, 'type', 'Mobile')
                WHERE dr.customer_mobile IS NOT NULL AND dr.customer_mobile != ''
            ) phones
        ) AS phone_jsonb,
        COALESCE(dr.customer_phone, '') || ' ' || COALESCE(dr.customer_mobile, '') AS phone_fts,
        -- Address as background
        NULLIF(CONCAT_WS(', ',
            NULLIF(dr.customer_address, ''),
            NULLIF(dr.customer_suburb, ''),
            NULLIF(dr.customer_city, ''),
            NULLIF(dr.customer_postcode, '')
        ), '') AS background,
        parse_ddmmyyyy(dr.customer_dob::text) AS date_of_birth,
        COALESCE(parse_ddmmyyyy(dr.date_opened::text), dr.uploaded_at)::timestamptz AS first_seen,
        -- Deduplication key
        COALESCE(
            NULLIF(dr.customer_email, ''),
            dr.customer_name || '|' || COALESCE(dr.customer_phone, '')
        ) AS dedup_key
    FROM dispatch_report dr
    WHERE dr.customer_name IS NOT NULL AND dr.customer_name != ''
    GROUP BY
        dedup_key,
        dr.customer_name,
        dr.customer_email,
        dr.customer_phone,
        dr.customer_mobile,
        dr.customer_address,
        dr.customer_suburb,
        dr.customer_city,
        dr.customer_postcode,
        dr.customer_dob,
        dr.date_opened,
        dr.uploaded_at
    ORDER BY dedup_key, MIN(dr.id)
) lc;

-- ---------------------------------------------------------------------------
-- 6. Performance indexes
-- ---------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_dispatch_report_plan_id ON dispatch_report(plan_id);
CREATE INDEX IF NOT EXISTS idx_dispatch_report_cancelled ON dispatch_report(cancelled);
CREATE INDEX IF NOT EXISTS idx_dispatch_report_customer_name ON dispatch_report(customer_name);

-- Index on legacy_payments if it's a table (not a view)
DO $$ BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'legacy_payments' AND table_type = 'BASE TABLE'
    ) THEN
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_legacy_payments_dd_plan_id ON legacy_payments(dd_plan_id)';
    END IF;
    -- Also index the source payments table if it exists with dd_plan_id
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'payments' AND column_name = 'dd_plan_id'
    ) THEN
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_payments_dd_plan_id ON payments(dd_plan_id)';
    END IF;
END $$;

-- ---------------------------------------------------------------------------
-- 7. Grant access on views to authenticated role
-- ---------------------------------------------------------------------------
GRANT SELECT ON deals_unified TO authenticated;
GRANT SELECT ON payments_crm TO authenticated;
GRANT SELECT ON payment_schedule_crm TO authenticated;
GRANT SELECT ON contacts_summary TO authenticated;
